//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlacaYazilimWebSiteEntities : DbContext
    {
        public AlacaYazilimWebSiteEntities()
            : base("name=AlacaYazilimWebSiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DownloadLink> DownloadLink { get; set; }
        public DbSet<DuyuruHaber> DuyuruHaber { get; set; }
        public DbSet<FirmaBilgileri> FirmaBilgileri { get; set; }
        public DbSet<Kullanicilar> Kullanicilar { get; set; }
        public DbSet<MusteriYazi> MusteriYazi { get; set; }
        public DbSet<Popup> Popup { get; set; }
        public DbSet<Referans> Referans { get; set; }
        public DbSet<Urun> Urun { get; set; }
        public DbSet<UrunGrup> UrunGrup { get; set; }
    }
}
