//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DownloadLink
    {
        public int DownloadId { get; set; }
        public string DownloadAdi { get; set; }
        public string DownloadUrl { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> Aktif { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
