//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DuyuruHaber
    {
        public int DuyuruId { get; set; }
        public string DuyuruBaslik { get; set; }
        public string DuyuruKisa { get; set; }
        public string Duyuru { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> Sira { get; set; }
        public Nullable<bool> Aktif { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
