//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmaBilgileri
    {
        public int Id { get; set; }
        public string FirmaAdi { get; set; }
        public string FirmaAdiUzun { get; set; }
        public string Adres { get; set; }
        public string Telefon1 { get; set; }
        public string Telefon2 { get; set; }
        public string CepTelefon { get; set; }
        public string Fax { get; set; }
        public string IletisimMail { get; set; }
        public string DestekMail { get; set; }
        public string SatisMail { get; set; }
        public Nullable<bool> Aktif { get; set; }
        public string AdminDomainAddress { get; set; }
    }
}
