//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriYazi
    {
        public int MusteriYaziId { get; set; }
        public string Isim { get; set; }
        public string Unvan { get; set; }
        public string MusteriYazi1 { get; set; }
        public string ResimUrl { get; set; }
        public string FirmaUrl { get; set; }
        public Nullable<int> Sira { get; set; }
        public Nullable<bool> Aktif { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
