//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referans
    {
        public int ReferansId { get; set; }
        public string ReferansFirmaAdi { get; set; }
        public string ResimUrl { get; set; }
        public string FirmaUrl { get; set; }
        public Nullable<int> Sira { get; set; }
        public Nullable<bool> Aktif { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> ShowInSlider { get; set; }
    }
}
