//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunGrup
    {
        public int UrunGrupId { get; set; }
        public Nullable<int> AnaGrupId { get; set; }
        public string UrunGrupAdi { get; set; }
        public Nullable<bool> Aktif { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
    }
}
